### Create Developer Test
POST http://127.0.0.1:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FULL_STACK",
  "experienceYears": 12,
  "memberId": "Mani",
  "name": "mouse",
  "age": 32
}